#!/bin/bash
NAMESPACED=( $(oc get crd -o=custom-columns='Name:.metadata.name,Namespaced:.spec.scope' | tail -n +2 | grep Namespaced | awk '{print $1}' ))
LIST=$(echo $(printf -- "%s," ${NAMESPACED[*]}))
echo "$(oc get ${LIST%?})"
